services:
  # API
  stringal-api:
    build: ./.docker/api
    container_name: stringal-api
    hostname: stringal-api
    depends_on:
      - stringal-mysql
      - stringal-redis
    networks:
      - stringal-net
    ports:
      - "5173:5173"
    volumes:
      - ./stringal-api:/var/www/html

  # API Horizon/Scheduler
  stringal-api-horizon:
    build: ./.docker/api-horizon
    container_name: stringal-api-horizon
    hostname: stringal-api-horizon
    depends_on:
      - stringal-mysql
      - stringal-redis
    networks:
      - stringal-net
    volumes:
      - ./stringal-api:/var/www/html

  # API Reverb
  #stringal-api-reverb:
  #  build: ./.docker/api-reverb
  #  container_name: stringal-api-reverb
  #  hostname: stringal-api-reverb
  #  depends_on:
  #    - stringal-mysql
  #    - stringal-redis
  #  networks:
  #    - stringal-net
  #  volumes:
  #    - ./stringal-api:/var/www/html

  # API web
  stringal-api-web:
    image: nginx:latest
    container_name: stringal-api-web
    hostname: stringal-api-web
    depends_on:
      - stringal-api
    links:
      - stringal-api
    networks:
      - stringal-net
    ports:
      - "8060:80"
      - "8061:443"
    volumes:
      - ./stringal-api:/var/www/html
      - ./.docker/nginx/ssl:/etc/nginx/ssl
      - ./.docker/nginx/api-web.conf:/etc/nginx/conf.d/default.conf

  # API Reverb web
  #stringal-api-reverb-web:
  #  image: nginx:latest
  #  container_name: stringal-api-reverb-web
  #  hostname: stringal-api-reverb-web
  #  depends_on:
  #    - stringal-api-reverb
  #  links:
  #    - stringal-api-reverb
  #  networks:
  #    - stringal-net
  #  ports:
  #    - "9060:80"
  #    - "9061:443"
  #  volumes:
  #    - ./stringal-api:/var/www/html
  #    - ./.docker/nginx/ssl:/etc/nginx/ssl
  #    - ./.docker/nginx/api-reverb-web.conf:/etc/nginx/conf.d/default.conf

  # MySQL
  stringal-mysql:
    image: mariadb:latest
    container_name: stringal-mysql
    hostname: stringal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 20240101
    networks:
      - stringal-net
    ports:
      - "3360:3306"
    volumes:
      - ./.docker_data/mysql:/var/lib/mysql

  # Redis
  stringal-redis:
    image: redis:alpine
    container_name: stringal-redis
    hostname: stringal-redis
    command: "redis-server --requirepass 20240101"
    networks:
      - stringal-net
    ports:
      - "6360:6379"

networks:
  stringal-net:
    driver: bridge
